services:
  - name: nasa-ultra-master-vx
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:10000
    envVars:
      - key: FLASK_ENV
        value: production
